config/routes.rb
Rails.application.routes.draw do
  resources :tasks	  
  root to: "tasks#index"
end	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index	  
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)	    
    if @task.save	    
     redirect_to tasks_path
    else	    
      render :new	      
  end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy

  end	  

  private

  def task_params
    params.require(:task).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VueTaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

  <div style="width: 300px;">
    <%= form_for(@task) do |f| %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title, size: 50 %>
      </div>
      <div>
        <%= f.label :description %>
        <%= f.text_area :description, size: "60*10" %>
      </div>
      <%= f.submit '送信' %>
    <% end %>
  </div>

  <p><%= link_to '一覧に戻る', tasks_url %></p> 

app/views/tasks/index.html.erb
  <h1>タスクの一覧</h1>

  <table>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Description</th>
    </tr>
      <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= link_to '詳細', task_path(task) %></td>
      <td><%= link_to '編集', edit_task_path(task) %></td>
      <td><%= link_to '削除', task_path(task), method: :delete %></td>
    </tr>
    <% end %>
  </table>
  <p><%= link_to 'ToDoの作成', new_task_path %></p> 

app/views/tasks/new.html.erb
<h1>タスクの新規作成</h1>
<div style="width: 300px;">
  <%= form_for(@task) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, size: 50 %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: "60*10" %>
  </div>
    <%= f.submit '送信' %>
  <% end %>
</div>
<p><%= link_to '一覧に戻る', tasks_url %></p> 

app/views/tasks/show.html.erb
  <h1>タスクの詳細</h1>

  <table>
    <tr>
      <th>Title</th>
      <td><%= @task.title %></td></tr>
    <tr>
      <th>Description</th>
      <td><%= @task.description %></td>
    </tr>

  </table>
  <p><%= link_to '一覧に戻る', tasks_url %></p> 